### ISSUE TITLE
ToDo

### ISSUE THREAD

**Issue by xFireBerg** [xFireBerg/BIM493_Project#1]
- Everything!
- I just created signup/login pages using the essential UI kit from syncfusion. Added support for saving email, passwords, etc. locally. May need to move it to DB support on azure or firebase
- Need to get the license for syncfusion first, since without a warning pops up on every running of the app.
- I think aiming for a view like [this](https://github.com/iSoron/uhabits/blob/dev/screenshots/uhabits5.png) would be a good start. 
- Maybe the textbox/scheduler from the kit could be used. Will have to readup

**Comment by zokatr** [comment]
- [x] Page Designing

- [x] Add funtion to the UI

- [x] Create Database

- [x] Connect Database To Views

- [x] Login - Sign Up database connection

- [x] Participant Request Feature !!!

**Comment by zokatr** [comment]
Done
